language: python
python:
  - 3.8
  - 3.7
sudo: false

cache:
  directories:
    - $PIP_CACHE_DIR
    - $PIPENV_CACHE_DIR

env:
  CODECOV_TOKEN:
    secure: "R8j3dn7hMp45rFO/PbP+5FOob4wo9nONhb07kVcvoasRTWiVIHb3/9ckOT7vgnS2DJaRIQPXnG89fHv42xQmtH+jJlz4yoaheyI7mUh/2IbGfdg1I9cjaSg19WnKFQ/3/jIzoN923xLbWxVMmczlg/lvPEAf+QA/AyAxPe9mrzlknEb5N5Er/VgHu7HfKX6NBfIKS9EOlj24Bm9Wss75CbFfSlLkJQIbRqi9RHiNkGs9mbCAW4vcPSoOsYAyVOS+Bkh9CYCbZNT33YMiY6kf+5mpkjF5LKfOYZSkWz/vs/gA8Zepey0bPYFjAzDZARbXeCm/J/gJ9v44eqnCbHzgS5ikIwZ3DG+VmMOci0i4KnsFeq07ZRHyfJfpGhW62KVdJFrnwJxRfNsqGuUtuC5bT6xFzoSFrHdKDb+gXwi0X8PFXnIkd5T4MK3owD+OyHp4iVmYsqP4aooc3h68+9pKX0c/TpqcJqDgKl3o73TsTurQo/l6fvr0ufnFrUnFmXr+ZkkjAxtYYiELfh1JP+MWS06OtUxrx37B6yHQF+D8MkaM2gw1KtSZOxbgkat+vc7JT8ez1Xt6qg7OWb+JogqDJid3RHqN3wxGuZHUynJpIpJgjF0z64ibnJEx7pF61r0hPCQQjvNCeweD+O1AmgP2462S3C4FPTZcbldm2G98G68="
  global:
    - PIP_CACHE_DIR=$HOME/.cache/pip
    - PIPENV_CACHE_DIR=$HOME/.cache/pipenv

install:
  - "pip install pipenv"
  - "pipenv install --dev --skip-lock"

# Test script
script:
  invoke test &&
  coverage report &&
  codecov

stages:
  - format
  - test
  - e2e


jobs:
  include:
    - stage: format
      script: make refactor
      name: "Formatting"

    - stage: e2e
      script: invoke e2e
      
    - stage: deploy
      deploy:
        provider: heroku
        api_key:
          secure: "FtzXXDWj/HbkkiNJoQbzo853qaKl+CqO2KidZHtWnuKy1r41oL+XPukppvm1diOic4y5+qGhosbeZZN1m2QQMtUTD0TthWx84+ElVONx+uNubX1n9bWHITygpA5MDlTAg21TZITj7EPSNWGyDFnAbAjKTJgRaFHoiQjjKLHnScccAerE/uHiS6IJfzHh3oXJvygXHhZOLPBjqUjCK7DpYmG7F9pyXUANi+EKtSTDTeDG3xsehkwmDoN0U/G5rhLePtmXk1gVnRdg2LmXCRwkul7Hl9EXLcBy3/BqW4C4YYqg3KuKXwE+jRwTJTp1AzZV5I4G5A6I6ZNXy3eybGnKNlu0blyNKCIsF9tIRIFs36OW1NtQ6Acr30fxTaNSFKc0+EEwkuRHOl/a2qwVekB4Ls1jH/M8YqC4ZyOD7C82KD0bAAOZ77D8Z8fRGF7mVz9ZgfJ2WdE+di2Tubb7WX7IZ1h0ULrp74W/fAQmjzpUMWLTXtC6UAsTYCh8So5hjS/QeI5ZyAsDZz1jxr141Umng9Bi1zqpcLe3lSWasXwTQPslO2VOHQg71uj84MuncDSwUicoZDjkX5GU+wvq8ZVJ/89w6k7uvQqddA72zKMozx3I9asRJxkq/bpgjZjGRcOdh4ZCi83SlimbhRfcx8gDWgimSkLkQxvdwHGEwZgSb+8="
        app: coronavirus-us-api
        on:
          repo: Spiderpig86/coronavirus-us-api
