version: '3.3'

services:
  api:
    build: .
    command: uvicorn backend.main:api --host 0.0.0.0 --port 8000 --reload
    restart: always
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true